#!/usr/bin/env bash
# One-command CA + server identity bootstrap (SERVER_SPEC §3). Run ONCE.
#
#   ./bootstrap.sh nas.example.com [extra-hostname-or-ip ...]
#
# Produces in this directory:
#   ca.key      CA root private key  -> MOVE OFFLINE after setup (see below)
#   ca.crt      CA certificate       (mounted read-only into nginx)
#   server.key  server TLS key       (mounted read-only into nginx)
#   server.crt  server TLS cert      (mounted read-only into nginx)
#   crl.pem     empty initial CRL    (regenerated by revoke.sh)
#
# Validity (decision D1 — WireGuard-key semantics, no renewal flow):
#   CA 30 years, server 10 years; device certs (signed at enrollment) 25 years.
set -euo pipefail

# Git Bash (MSYS) rewrites /CN=... arguments into Windows paths; disable that.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'

cd "$(dirname "$0")"

CA_DAYS=10950      # 30 years
SERVER_DAYS=3650   # 10 years
CRL_DAYS=3650

if [[ $# -lt 1 ]]; then
    echo "usage: ./bootstrap.sh <public-hostname> [extra-hostname-or-ip ...]" >&2
    exit 1
fi
HOSTNAME="$1"; shift

if [[ -f ca.key || -f ca.crt ]]; then
    echo "ERROR: a CA already exists here. Refusing to overwrite." >&2
    echo "If you truly want a fresh CA (this invalidates EVERY enrolled" >&2
    echo "device), delete ca.* server.* crl.pem manually first." >&2
    exit 1
fi

SAN="DNS:$HOSTNAME"
for extra in "$@"; do
    if [[ "$extra" =~ ^[0-9.]+$ ]]; then SAN="$SAN,IP:$extra"; else SAN="$SAN,DNS:$extra"; fi
done

echo "==> CA root (EC P-256, $CA_DAYS days)"
# Explicit config instead of -addext: the default openssl.cnf contributes its
# own basicConstraints, and duplicate extensions break strict (Go) parsers.
cat > .ca.cnf <<'EOF'
[req]
distinguished_name = dn
x509_extensions = v3_ca
prompt = no
[dn]
CN = Sambaloader CA
[v3_ca]
basicConstraints = critical,CA:TRUE,pathlen:0
keyUsage = critical,keyCertSign,cRLSign
subjectKeyIdentifier = hash
EOF
openssl ecparam -name prime256v1 -genkey -noout -out ca.key
openssl req -x509 -new -key ca.key -sha256 -days "$CA_DAYS" -config .ca.cnf -out ca.crt

echo "==> Server certificate ($SERVER_DAYS days, SAN: $SAN)"
printf "subjectAltName=%s\nextendedKeyUsage=serverAuth\nbasicConstraints=CA:FALSE\n" "$SAN" > .server.ext
openssl ecparam -name prime256v1 -genkey -noout -out server.key
openssl req -new -key server.key -subj "/CN=$HOSTNAME" -out .server.csr
openssl x509 -req -in .server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -sha256 -days "$SERVER_DAYS" -extfile .server.ext -out server.crt

echo "==> Empty initial CRL (revoke.sh regenerates it)"
mkdir -p .crldb
touch .crldb/index.txt
echo 1000 > .crldb/crlnumber
cat > .crldb/ca.cnf <<EOF
[ca]
default_ca = local
[local]
database = .crldb/index.txt
crlnumber = .crldb/crlnumber
default_md = sha256
default_crl_days = $CRL_DAYS
EOF
openssl ca -config .crldb/ca.cnf -gencrl -keyfile ca.key -cert ca.crt -out crl.pem 2>/dev/null

rm -f .ca.cnf .server.ext .server.csr

echo ""
echo "Done. CA fingerprint (the admin page shows this during enrollment):"
openssl x509 -in ca.crt -noout -fingerprint -sha256
cat <<'EOF'

############################################################################
#                                                                          #
#   MOVE ca.key OFF THIS MACHINE NOW.                                      #
#                                                                          #
#   Server operation does NOT need it. It is required only while           #
#   enrolling a new device or revoking one — copy it back into this        #
#   directory for those minutes, then delete it again.                     #
#                                                                          #
#   A CA key sitting on an internet-connected server defeats the entire    #
#   security design. Offline storage: USB stick, password manager, etc.    #
#                                                                          #
############################################################################
EOF
